export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGIN_BLOCKED_EMAIL_NOT_VERIFIED = 'LOGIN_BLOCKED_EMAIL_NOT_VERIFIED',
  LOGOUT = 'LOGOUT',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
}
